Test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,4 +1,10 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-npm test
+if npm run prettier; then
+  echo "Prettier passed ✅"
+  exit 0
+else
+  echo "Tests failed ❌"
+  exit 1
+fi
