Test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -9,4 +9,12 @@ else
   exit 1
 fi
 
-npm run test
+if npm run test; then
+  echo "Tests passed ✅"
+  exit 0
+else
+  echo "Tests failed ❌"
+  exit 1
+fi
+
+
