Test

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -7,3 +7,11 @@ else
   echo "Tests failed ❌"
   exit 1
 fi
+
+
+if npm run test; then
+  echo "Tests passed ✅"
+else
+  echo "Tests failed ❌"
+  exit 1
+fi
