Done

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -21,6 +21,11 @@ jobs:
         run: |
           npm install
           npm update
+          if npm test; then
+            echo "Tests passed"
+          else
+            echo "Tests failed" && exit 1
+          fi
           npm run build
 
       - name: 📂 Sync files
